### Copyright (C) 2015 Peter Williams <pwil3058@gmail.com>
###
### This program is free software; you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation; version 2 of the License only.
###
### This program is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.
###
### You should have received a copy of the GNU General Public License
### along with this program; if not, write to the Free Software
### Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

# Help maintain compatability between Python 2 and 3

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

try:
    import cPickle as pickle
    PICKLE_PROTOCOL = pickle.HIGHEST_PROTOCOL
except ImportError:
    import sys
    import pickle
    # WORKAROUND: Make sure that Python 2.7.x can read pickle files generated by Python 3.4.x
    PICKLE_PROTOCOL = pickle.HIGHEST_PROTOCOL if int(sys.version[0]) < 3 else 2
